"""update-transactions-add-tier

Revision ID: 066ce60d5330
Revises: ad167b54971f
Create Date: 2023-12-13 17:14:00.793780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066ce60d5330'
down_revision: Union[str, None] = 'ad167b54971f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('tier', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'tier')
    # ### end Alembic commands ###
