"""update-transactions-add-created_at

Revision ID: 5f4c42edbc4f
Revises: 066ce60d5330
Create Date: 2023-12-13 17:18:19.486442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision: str = '5f4c42edbc4f'
down_revision: Union[str, None] = '066ce60d5330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('created_at', sa.DateTime, server_default=func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'created_at')
    # ### end Alembic commands ###
